- name: Install nginx and start
  hosts: web
  become: yes #to become root -b in adhoc command 
  tasks: 
  - name: "Install nginx" 
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: "Start/run nginx"
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
