- name: taking variables from vars_yaml file
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: "printing variables info"
    debug:
      msg: "Hi, We are learning {{course}} from Trainer {{trainer}}, Duration is {{duration}}."