- name: taking variables from files
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: "printing variables info"
    ansible.builtin.debug:
      msg: "Hi, We are learning {{course}} from Trainer {{trainer}}, Duration is {{duration}}."