- name: "Varibales from prompt"
  hosts: localhost
  vars_prompt:
  - name: "username"
    prompt: "What is your username"
    private: false
  - name: "Password"
    prompt: "what is your password"
    private: true
  tasks:
  - name: printing variables info
    ansible.builtin.debug:
      msg: "Hi, We are learning {{course}} from Trainer {{trainer}}, Duration is {{duration}}."
