- name: taking variables from files
  hosts: localhost
  vars:
  - timings: :07:15 AM IST"
  tasks:
  - name: "printing variables info"
    ansible.builtin.debug:
      msg: "Hi, We are learning {{course}} from Trainer {{trainer}}, Duration is {{duration}} Timings are {{timings}}."