- name: taking variables from files
  hosts: localhost
  vars:
    WISHES: "Good Luck from play variable"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: WISHES
    prompt: Enter your Wishes
    private: false
    

  tasks:
  - name: "printing variables and the preference is"
    # vars:
    #   WISHES: wishes from task variable
    ansible.builtin.debug:
      msg: "Hi,  {{WISHES}}"
  

