- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true
  - name: Print the output
    ansible.builtin.debug:
      msg: "And the o.p is {{USER}}"