- name: conditions
  hosts: localhost
  vars_prompt:
  - name: "number"
    prompt: "Enter a number"
    private: false
  tasks:
  - name: less than 10
    ansible.builtin.debug:
      msg: "Yes, {{number}} less than 10"
    when: number | int < 10

  - name: greater than 10
    ansible.builtin.debug:
      msg: "Yes, {{number}} greater than 10"
    when: number | int >= 10