- name: conditions
  hosts: localhost
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "Hi {{hurray | default('cherry')}}"

- name: upper case
  hosts: localhost
  vars:
    hurray: cherry
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "Hi {{hurray | upper}}"