- name: conditions
  hosts: localhost
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "Hi {{hurray | default('cherry')}}"

  - name: upper case
    ansible.builtin.debug:
      msg: "Hi {{"hurray" | upper}}"