- name: conditions
  hosts: localhost
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "Hi {{hurray | default('cherry')}}"

- name: upper case
  hosts: localhost
  vars:
    hurray: cherry
  tasks:
  - name: upper
    ansible.builtin.debug:
      msg: "Hi {{hurray | upper}}"

- name: lower case
  hosts: localhost
  vars:
    hurray: MANISHA
  tasks:
  - name: lower
    ansible.builtin.debug:
      msg: "Hi {{hurray | lower}}"

- name: min
  hosts: localhost
  vars:
    age: [21,33,89,9,56]
  tasks:
  - name: min age
    ansible.builtin.debug:
      msg: "min age {{age | min}}, max age is {{age | max}}"

# - name: max
#   hosts: localhost
#   age:
#   - 14
#   - 25
#   - 16
#   tasks:
#   - name: min age
#     ansible.builtin.debug:
#       msg: "maximum nage {{age | max}}"

- name: Dict to list
  hosts: localhost
  vars:
   Experience: #map/dict
      devops: 2
      testing: 3
  tasks:
  - name: "COnvert dict to list"
    ansible.builtin.debug:
      msg: "before conversion, dict is  {{Experience}}"

  - name: "COnvert dict to list"
    ansible.builtin.debug:
      msg: "the converted list is  {{Experience | dict2items}}"


- name: list to dict
  hosts: localhost
  vars:
    Tools: #list
    - Ansible
    - Jenkins
    - terraform
  tasks:
  - name: "COnvert list to dict"
    ansible.builtin.debug:
      msg: "before conversion, dlist is  {{Tools}}"
  tasks:
  - name: "COnvert list to dict"
    ansible.builtin.debug:
      msg: "the converted list is  {{Tools | items2dict}}"


- name : remove duplicates
  hosts: localhost
  vars:
    age: [21,,21,33,89,9,56,9]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "AFter removing dups {{age | unique}}"